### PR TITLE
US1 Farag

### PR DESCRIPTION
**Pull request by fkwafi**
could you please review my code!!

### CODE REVIEW

**Review by MayilaPaerhati — APPROVED** [review]
good job

**Review by yadikar211 — APPROVED** [review]

**Comment by yadikar211** [comment]
good job

**Review by tulayer — APPROVED** [review]
Great job!

**Review by glr425 — APPROVED** [review]
good job!

**Review by JasminePa — APPROVED** [review]
well done!!

**Review by DenysVorob — APPROVED** [review]
I have never ever seen a better job!!!

**Review by anarissoy — APPROVED** [review]

**Review by anarissoy — CHANGES_REQUESTED** [review]
Farag there is a conflict on LoginPage, you should not have commit and push LoginPage. pls fix it

**Review by KamranABD-B27 — APPROVED** [review]
Perfect Farag!

**Pull request closed without merging**
